## Install and import numpy

In [6]:
%pip install numpy
import numpy as np
np.__version__

'2.1.1'

## How to Create a Numpy array

In [7]:
np.array([1,2,3,4]) 

array([1, 2, 3, 4])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 3.22647253e-307]])

In [12]:
np.arange(0,10,2)  

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,10,2)  

array([ 0., 10.])

In [14]:
np.random.rand(5)  

array([0.00469685, 0.89373623, 0.20193564, 0.17775599, 0.71394133])

## size & shape ,Reshape

In [16]:
arr = np.array([
    [1,2,3],[4,5,6]
])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr.size

6

In [19]:
arr = np.array([
    [1,2,3],[4,5,6]
])
arr.ndim

2

In [20]:
arr = np.array([1,2,3,4,5,6])

np.reshape(arr,shape=(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

## Sort element

In [25]:
arr = np.array([1,3,2,6,3,6,3,7,4,5,60])
np.sort(arr)

array([ 1,  2,  3,  3,  3,  4,  5,  6,  6,  7, 60])

## list vs python numpy

### List


In [40]:
import time

a =  list(range(0,100000))
b = list(range(100000,200000))
c = []

start =  time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
end = time.time()

print(end-start)

0.023549556732177734


### numpy

In [41]:
import numpy as np
import time

a = np.arange(0,100000)
b = np.arange(100000,200000)

start = time.time()
c = a + b
end = time.time()
print(end-start)

0.0024406909942626953
